[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="product_img_root" type="java.lang.String" --]
[#-- @ftlvariable name="__RequestContext" type="com.brains.prj.tianjiu.order.mvc.RequestContext" --]

[#macro block name][/#macro]
[#macro override name][/#macro]
[#macro super][/#macro]
[#macro extends name][/#macro]
[#macro OrderControl path para][/#macro]
[#macro ProductUrl pid][/#macro]
[#macro OrderStateString os][/#macro]
[#macro OrderPayString os][/#macro]
[#macro OrderOpString ocd os pm][/#macro]